export const FETCH_EVENT_START = "FETCH_EVENT_START";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const CREATE_EVENT_START = "CREATE_EVENT_START";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const BEGIN_MATCH_START = "BEGIN_MATCH_START";
export const BEGIN_MATCH_SUCCESS= "BEGIN_MATCH_SUCCESS";
export const EVENT_ERROR = "EVENT_ERROR";